repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, main, --branch, dev]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      exclude: ^(docs/conf.py|tests/)
      additional_dependencies: [
        flake8-bugbear,
        flake8-print,
        flake8-docstrings,
        pep8-naming,
      ]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black
      args: [--check, --diff, src]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black-jupyter
        args: [--check, --diff]
        files: (docs/how-to|docs/getting-started)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: src

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--check-only, -v]

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
